

```{r}
library(tidyverse)
library(rstatix)

onedrive_path <- "~/OneDrive - Northwestern University/Project folders/CANDO 16S/"

weird_period <- data.frame(x1 = 170, x2 = 465)
```

```{r}
ps_rel_list <- readRDS(file.path(onedrive_path, "./parsed data/ps_rel_list.RDS"))

table_rel <- ps_rel_list[["ab"]] %>%
  pivot_longer(cols = !seq, names_to = "sample", values_to = "ab") %>%
  left_join(ps_rel_list[["tax"]], join_by(seq)) %>%
  left_join(ps_rel_list[["meta"]], join_by(sample)) %>%
  mutate(date = mdy(date)) %>%
  filter(!is.na(Genus))

```

# Dechloromonas check
```{r}
dechloro_blast <- readRDS(file.path(onedrive_path, "./parsed data/dechloro_blast.RDS")) %>%
  filter(!str_detect(Species, "midas_s")) %>%
  select(query, Species)

# manual rename, cant figure out automated way lol 
table_rel <- table_rel %>%
  mutate(Species = case_when(seq == "e9c834248ac7a70892628dea785c1c92" ~ "Azonexus_phosphoritropha",
                             seq == "9372a32bd76e3ad14b37c40d7d43c4cc" ~ "Azonexus_agitata",
                             seq == "c7500c4281b7f60cc4ffa07b17485bf9" ~ "Azonexus_hortensis",
                             .default = Species))

table_rel %>%
  filter(Genus == "Azonexus") %>%
  ggplot(., aes(x = day, y = ab, color = Species)) +
  geom_point() + 
  geom_line()

```
# PAO and GAO plots by time
```{r}

list_plot_pao_gao <- c("Ca_Accumulibacter", "Ca_Competibacter", "Ca_Phosphoribacter", "Tetrasphaera",
                       "Defluviicoccus", "Azonexus")

table_rel %>%
  filter(Genus %in% list_plot_pao_gao) %>%
  select(day, Genus, ab) %>%
  group_by(day, Genus) %>%
  summarise(sum_ab = sum(ab)) %>%
  ggplot(., aes(x = day, y = sum_ab)) +
  facet_wrap(~Genus, scales = "free") +
  geom_rect(aes(xmin = weird_period$x1, xmax = weird_period$x2, ymin = 0, ymax = Inf), 
              fill = "lemonchiffon1", color = "lemonchiffon1") +
  geom_point() +
  theme_classic()


```

# Correlation matrices

```{r}

corr_genus_against_all <- function(genus, wide_table){
  df_tmp <- wide_table %>%
    cor_test(paste(genus), method = "spearman") %>%
    filter(p <= 0.05)
  
}

table_wide <- table_rel %>%
  select(date, Genus, ab) %>%
  group_by(date, Genus) %>%
  summarise(sum_ab = sum(ab)) %>%
  pivot_wider(id_cols = date, names_from = Genus, values_from = sum_ab) %>%
  column_to_rownames("date")

columns_pass <- which(colSums(table_wide != 0) >= 37/2)

table_wide_filt <- table_wide[, columns_pass]

list_corr_pao_gao <- c("Ca_Accumulibacter", "Ca_Competibacter", "Ca_Phosphoribacter")

corr_list <- list() 
corr_list <- lapply(list_corr_pao_gao, FUN = corr_genus_against_all, wide_table = table_wide_filt)
names(corr_list) <- list_corr_pao_gao


```







